// <auto-generated />
using System;
using DiziSearch.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DiziSearch.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200226190634_Initial2")]
    partial class Initial2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("DiziSearch.Models.Dizi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<string>("Alias");

                    b.Property<bool>("Approved");

                    b.Property<string>("ApprovedBy");

                    b.Property<string>("Cast");

                    b.Property<string>("Country");

                    b.Property<string>("Description");

                    b.Property<string>("Genre");

                    b.Property<decimal>("IMDBScore");

                    b.Property<string>("IMDBScoreStr");

                    b.Property<string>("Image");

                    b.Property<bool>("InFront");

                    b.Property<string>("Name");

                    b.Property<string>("UploadedBy");

                    b.Property<DateTime>("Year");

                    b.HasKey("Id");

                    b.ToTable("Diziler");
                });

            modelBuilder.Entity("DiziSearch.Models.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<string>("Alias");

                    b.Property<bool>("Approved");

                    b.Property<string>("ApprovedBy");

                    b.Property<string>("CurrentLink");

                    b.Property<DateTime>("Date");

                    b.Property<int>("DiziId");

                    b.Property<string>("Durum");

                    b.Property<string>("EditedBy");

                    b.Property<string>("Ep")
                        .IsRequired();

                    b.Property<string>("EpName");

                    b.Property<string>("Link1");

                    b.Property<string>("Link2");

                    b.Property<string>("Link3");

                    b.Property<string>("Link4");

                    b.Property<string>("Link5");

                    b.Property<string>("Name");

                    b.Property<string>("Season")
                        .IsRequired();

                    b.Property<string>("Spoiler");

                    b.Property<string>("Subtitle");

                    b.Property<string>("UploadedBy");

                    b.HasKey("Id");

                    b.HasIndex("DiziId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("DiziSearch.Models.Episode", b =>
                {
                    b.HasOne("DiziSearch.Models.Dizi", "Dizi")
                        .WithMany()
                        .HasForeignKey("DiziId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
